### ISSUE TITLE
Potential flashpoints for some bugs

### ISSUE THREAD

**Issue by aturX** [saruman420/golomtrader#1]
1. ownership

`address payable owner;`  

I can't see the owner externally, and I can't replace it either 

So I suggest: `address payable public owner;`   In addition, add a function to change the ownership

If the owner leaks, the project will go into full risk.

2.  feeTo

`owner.transfer(_uintArgs[3]); // fee transfer to owner` 
`//1-totalAmt,//2-deadline,//3-feeamt` 

During the sending process of the transaction, the transaction fee is not determined by the boundary value. However, when the UI parameters are passed to the wrong person, it will cause the user to lose most of the funds.

So I suggest: `feeamt < totalAmt * 0.1` ?  and `feeamt > 0`

**Comment by 0xsaruman** [comment]
Thanks for the suggestions, 

1. if Owner key is compromised then also the compromised wallet can easily change the wallet to its own using the function. So adding function to change ownership doesn't help here at all.
2. this contract is only for the initial phase where fees will be 0. There is EIP 712 signing which will clearly show the fees to user in metamask before signing.
